module.exports = {
    rootDir: ".",
    testEnvironment: "node",
    roots: ["<rootDir>"],
    testMatch: ["**/*.test.js", "**/*.spec.js"],
    setupFilesAfterEnv: ["jest-extended/all"],
    moduleNameMapper: {
        "^@root$": "<rootDir>/..",
        "^@root/(.*)$": "<rootDir>/../$1",
        "^@bin$": "<rootDir>/bin",
        "^@bin/(.*)$": "<rootDir>/bin/$1",
        "^@core$": "<rootDir>/core",
        "^@core/(.*)$": "<rootDir>/core/$1",
        "^@filters$": "<rootDir>/filters",
        "^@filters/(.*)$": "<rootDir>/filters/$1",
        "^@routes$": "<rootDir>/routes",
        "^@routes/(.*)$": "<rootDir>/routes/$1",
        "^@models$": "<rootDir>/models",
        "^@models/(.*)$": "<rootDir>/models/$1",
        "^@utils$": "<rootDir>/utils",
        "^@utils/(.*)$": "<rootDir>/utils/$1",
        "^@services$": "<rootDir>/services",
        "^@services/(.*)$": "<rootDir>/services/$1",
        "^@sockets$": "<rootDir>/sockets",
        "^@sockets/(.*)$": "<rootDir>/sockets/$1",
        "^@workers$": "<rootDir>/workers",
        "^@workers/(.*)$": "<rootDir>/workers/$1",
        "^@middleware$": "<rootDir>/middleware",
        "^@middleware/(.*)$": "<rootDir>/middleware/$1",
    },
};