#!/bin/bash

set -e
. /usr/share/debconf/confmodule
db_version 2.0

do_configure()
{

	# # clear up upgrade mess from previous install (sorry everyone)
	# rm /etc/apt/apt.conf.d/50unattended-upgrades.rej > /dev/null 2>&1 || true

    # # # php version
    # php_version=`php -v | head -n 1 | cut -d' ' -f2 | cut -d'.' -f1,2`
    # php_versioncode=`php -v | head -n 1 | cut -d' ' -f2 | cut -d'.' -f1,2 | tr -d .`

	# # # php module folder
	# extension_dir=`php -i | grep extension_dir | awk -F '=> ' '{print $3}'`

    # # # cpu architecture
    # cpu_architecture=`uname -m`

    # # # check PHP version
    # if [ "$php_version" != "7.2" ] ; then
    # 	echo "CRITICAL: This version of BUG requires PHP 7.2"
    #     exit 1
    # fi

	# printf "configuring apache2 to use /tmp                  ... "
	# if [ ! -f /etc/systemd/system/apache2.service ]
	# then
	# 	cp /usr/share/bbcnews-bug/install/apache2.service /etc/systemd/system/apache2.service || true
	# 	systemctl daemon-reload
	# 	printf "done\n"
	# else
	# 	printf "skipped\n"
	# fi

	# printf "installing PHP shared object libraries           ... "
	# if [ ! -f ${extension_dir}/mongodb.so ]
	# then
	# 	# .so files
	# 	cp /usr/share/bbcnews-bug/install/mongodb-${php_versioncode}-${cpu_architecture}.so ${extension_dir}/mongodb.so || true
	# fi
	# if [ ! -f /etc/php/${php_version}/mods-available/mongodb.ini ]
	# then
	# 	# .ini files
	# 	cp /usr/share/bbcnews-bug/install/mongodb.ini /etc/php/${php_version}/mods-available/mongodb.ini || true
	# fi
	# # enable
	# phpenmod mongodb > /dev/null 2>&1 || true
	# printf "done\n"

    # printf "deleting default apache config                   ... "
	# if [ -f "/etc/apache2/sites-enabled/000-default.conf" ]
	# then
	# 	a2dissite 000-default > /dev/null 2>&1 || true
	#     printf "done\n"
	# else
	# 	printf "skipped\n"
	# fi

	# printf "configuring apache fqdn                          ... "
	# if [ ! -f /etc/apache2/conf-enabled/fqdn.conf ]
	# then
	# 	echo "ServerName localhost" | tee /etc/apache2/conf-enabled/fqdn.conf > /dev/null 2>&1 || true
	#     printf "done\n"
	# else
	# 	printf "skipped\n"
	# fi

	# printf "configuring bug service to start at boot         ... "
	# systemctl enable bug.service > /dev/null 2>&1 || true
	# printf "done\n"

	# printf "installing autologin functionality               ... "
	# if [ ! -f "/etc/systemd/system/getty@tty1.service.d/override.conf" ]
	# then
	# 	mkdir -p /etc/systemd/system/getty@tty1.service.d || true
	# 	cp /usr/share/bbcnews-bug/install/override.conf /etc/systemd/system/getty@tty1.service.d/override.conf || true
	# 	printf "done\n"
	# else
	# 	printf "skipped\n"
	# fi

	# printf "configuring mongodb service                      ... "
    # if [ ! -f "/etc/systemd/system/mongodb.service" ]
	# then
    #     cp /usr/share/bbcnews-bug/install/mongodb.service /etc/systemd/system/ || true
    #     systemctl daemon-reload > /dev/null 2>&1 || true
    # fi
    # systemctl enable mongodb > /dev/null 2>&1 || true
	# systemctl start mongodb > /dev/null 2>&1 || true
	# printf "done\n"

	# printf "creating log folder                              ... "
	# mkdir /var/log/bbc > /dev/null 2>&1 || true
	# printf "done\n"

	# printf "setting log file permissions/owner               ... "
	# /bin/chmod 777 /var/log/bbc || true
	# printf "done\n"

	# printf "enabling mod_rewrite in apache                   ... "
	# a2enmod rewrite > /dev/null 2>&1 || true
	# printf "done\n"

	# printf "enabling bug application in apache               ... "
	# a2ensite bbcnews-bug > /dev/null 2>&1 || true
	# printf "done\n"

    # printf "adding bug sudo permissions                      ... "
    # patch -i /usr/share/bbcnews-bug/install/sudoers.diff -b -N -d /etc --ignore-whitespace > /dev/null 2>&1 || true
	# printf "done\n"

    # printf "setting grub timeout to 0                        ... "
    # patch -i /usr/share/bbcnews-bug/install/grub.diff -b -N -d /etc/default --ignore-whitespace > /dev/null 2>&1 || true
	# printf "done\n"

	# ###
	# # disable rpi boot logo
	# printf "configuring boot logo                            ... "
	# if [ -f "/boot/cmdline.txt" ]
	# then
	# 	if [ `grep -c nologo /boot/cmdline.txt` == 0 ]
	# 	then
	# 		sed -i ' 1 s/.*/& logo.nologo/' /boot/cmdline.txt
	# 	fi;
	# 	# enable bugboot service
	# 	sudo systemctl enable bugboot.service > /dev/null 2>&1 || true
	# 	printf "done\n"
	# else
	# 	printf "skipped\n"
	# fi;

	# printf "creating user                                    ... "
	# if [ `grep -c bug /etc/passwd` == 0 ]
	# then
	# 	/usr/sbin/useradd -d /usr/share/bbcnews-bug/bug_home -M -U -s /usr/share/bbcnews-bug/bug_home/login bug || true
	# 	printf "done\n"
	# else
	# 	printf "skipped\n"
	# fi;

	# printf "changing password settings for users             ... "
	# /usr/bin/passwd -d bug > /dev/null 2>&1 || true
	# printf "done\n"

	# printf "setting file permissions/owner                   ... "
    # /bin/chown -R bug.bug /usr/share/bbcnews-bug/bug_home/ || true
    # /bin/chmod -R 0777 /etc/bbcnews-bug/ || true
	# printf "done\n"

    # printf "> Installing composer libs                       ... \n"
    # mkdir -p /usr/share/bbcnews-bug/vendor || true
    # /bin/chmod -R 0777 /usr/share/bbcnews-bug/vendor || true
    # /bin/chmod -R 0777 /usr/share/bbcnews-bug/storage || true
    # /bin/chmod -R 0777 /usr/share/bbcnews-bug/bootstrap/cache || true
    # su -c "composer install -d /usr/share/bbcnews-bug/" -s /bin/bash bug || true
    # printf "                                                 ... done\n"

    # printf "setting up application                           ... "
    # php /usr/share/bbcnews-bug/artisan key:generate < /dev/null || true
    # printf "done\n"

	# printf "changing login permissions                       ... "
	# /bin/cp /usr/share/bbcnews-bug/install/xwrapper.config /etc/X11/Xwrapper.config < /dev/null || true
	# printf "done\n"

	# printf "selecting window manager                         ... "
    # /usr/bin/update-alternatives --set x-window-manager /usr/bin/ratpoison < /dev/null || true
	# printf "done\n"

	# printf "restarting apache                                ... "
	# /etc/init.d/apache2 reload > /dev/null 2>&1 || true
	# if [ $? != 0 ]
	# then
    #     /etc/init.d/apache2 restart > /dev/null 2>&1 || true
	# fi	
	# printf "done\n"

    # IP=`ip addr show scope global | grep inet | cut -d' ' -f6 | cut -d/ -f1`
    # IPS=`printf '%-15s' "$IP"`
}

setup_message()
{
	echo ""
    echo "                                                                              "
    echo "                                  *#######(                                   "
    echo "                               ###############                                "
    echo "                              #################.                              "
    echo "                             (##################                              "
    echo "                             (##################                              "
    echo "              ###(                                          ####              "
    echo "             ######(                                      ######              "
    echo "               ######*     #######################,     ######.               "
    echo "                 ###########################################.                 "
    echo "                   #######################################*                   "
    echo "                     ####################################                     "
    echo "                    #####################################                     "
    echo "                    #####################################                     "
    echo "                    #####################################                     "
    echo "            #####################################################,            "
    echo "           #######################################################            "
    echo "            ,###################################################(             "
    echo "                    #####################################                     "
    echo "                    #####################################                     "
    echo "                    #####################################                     "
    echo "                    *####################################                     "
    echo "                   ########################################                   "
    echo "                 ############################################                 "
    echo "               ######  ################################ #######               "
    echo "             ######     #############################     #######             "
    echo "           ######         #########################.        ######            "
    echo "           /###             (####################             ####            "
    echo "                                #############.                                "
	echo ""
	echo ""
	echo ""
	echo ""
	echo " Bug can be configured via the web UI at: http://$IPS"
	echo ""
	echo ""

}

case "$1" in
	configure)
		# after install
		# after reconfigure
		do_configure
		setup_message
	;;
esac

db_stop
