#!/bin/bash

# ###
# # disabling apache site
# printf "removing bug application from apache             ... "
# a2dissite bbcnews-bug > /dev/null 2>&1 || true
# printf "done\n"

# ###
# # remove startup service
# printf "removing bug startup service                     ... "
# systemctl disable bug.service > /dev/null 2>&1 || true
# printf "done\n"

# printf "Unpatching system files                          ... "
# ###
# # unpatch xwrapper file
# rm /etc/X11/Xwrapper.config > /dev/null 2>&1 || true
# ###

# ###
# # unpatch sudoers
# patch -R -i /usr/share/bbcnews-bug/install/sudoers.diff -b -N -d /etc --ignore-whitespace > /dev/null 2>&1 || true
# ###

# printf "done\n\n"
