info:
  name: mmi/getChassisSettings
  type: http
  seq: 4

http:
  method: POST
  url: https://{{HOSTNAME}}/mmi/api/jsonrpc
  body:
    type: json
    data: |
      {
        "jsonrpc": "2.0",
        "method": "mmi:3.6/chassis/GetChassisSettings",
        "params": {},
        "id": "GetChassisSettings"
      }
  auth:
    type: bearer
    token: "{{authToken}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
