# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BUG - Build, Test, Deploy

env:
    regsitry: "172.26.108.110"

on:
    push:
        branches:
            - main
        paths-ignore:
            - "**/README.md"
            - "docs/**"

jobs:
    backend:
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]
        defaults:
            run:
                working-directory: ./src
        steps:
            - uses: actions/checkout@v2
              name: Backend Install & Test using Node.js ${{ matrix.node-version }}
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm test
            - run: npm run build --if-present
    frontend:
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]
        defaults:
            run:
                working-directory: ./src/client
        steps:
            - uses: actions/checkout@v2
              name: Frontend Build & Test using Node.js ${{ matrix.node-version }}
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm test
            - run: npm run build --if-present
    docker:
        runs-on: self-hosted
        strategy:
            matrix:
                architecture: [linux/amd64, linux/arm64]
        defaults:
            run:
                working-directory: ./src
        steps:
            #Get the latest version of the repository
            - name: Checkout
              uses: actions/checkout@v2
            #Get the package.json version
            - uses: martinbeentjes/npm-get-version-action@master
              name: Get Backend Version
              id: backend-version
              with:
                  path: ./src
            - uses: martinbeentjes/npm-get-version-action@master
              name: Get Frontend Version
              id: frontend-version
              with:
                  path: ./src/client
            - name: Print Current Versions
              run: echo Building BUG with backend version ${{ steps.backend-version.outputs.current-version }} and frontend version ${{ steps.frontend-version.outputs.current-version }}
            #Docker Registry Login
            - name: Login to Harbor Registry
              uses: docker/login-action@v1
              with:
                  registry: ${{ env.regsitry }}
                  username: ${{ secrets.HARBOR_USER }}
                  password: ${{ secrets.HARBOR_KEY }}
            #Docker Buildx Setup
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1
              with:
                  buildkitd-flags: --debug
                  driver-opts: network=host
            - name: List available platforms
              run: echo ${{ steps.buildx.outputs.platforms }}
            #Docker Build Image and Push to Registry
            - name: Build and push to local registry
              uses: docker/build-push-action@v2
              with:
                  context: "./src"
                  dockerfile: ./src/Dockerfile
                  platforms: ${{ matrix.architecture}}
                  push: true
                  outpus: type=registry,registry.insecure=true
                  tags: ${{env.regsitry}}/bug/app:latest,${{env.regsitry}}/bug/app:${{steps.backend-version.outputs.current-version}}
            - name: Inspect
              run: |
                  docker buildx imagetools inspect ${{env.regsitry}}/bug/app:latest
