# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BUG - Build, Test, Deploy

env:
    regsitry: "172.26.108.110"

on:
    push:
        branches:
            - main
        paths-ignore:
            - "**/README.md"
            - "docs/**"

jobs:
    backend:
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]
        defaults:
            run:
                working-directory: ./src
        steps:
            - uses: actions/checkout@v2
              name: Backend Install & Test using Node.js ${{ matrix.node-version }}
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm test
            - run: npm run build --if-present
    frontend:
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]
        defaults:
            run:
                working-directory: ./src/client
        steps:
            - uses: actions/checkout@v2
              name: Frontend Build & Test using Node.js ${{ matrix.node-version }}
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm test
            - run: npm run build --if-present
    docker:
        runs-on: self-hosted
        services:
            registry:
                image: registry:2
                ports:
                    - 5000:5000
        defaults:
            run:
                working-directory: ./src
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1
              with:
                  buildkitd-flags: --debug
                  driver-opts: network=host
            - name: List available platforms
              run: echo ${{ steps.buildx.outputs.platforms }}
            - name: Build and push to local registry
              uses: docker/build-push-action@v2
              with:
                  context: "./src"
                  dockerfile: ./src/Dockerfile
                  push: true
                  tags: "${{env.regsitry}}/bug/app:latest"
            - name: Inspect
              run: |
                  docker buildx imagetools inspect ${{env.regsitry}}/bug/app:latest
