# .github/workflows/storybook.yml
name: "BUG Storybook"

on: push

jobs:
    test:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v1
            - run: npm install
            - uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  token: ${{ secrets.GITHUB_TOKEN }}
