name: BUG Client Tests

env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}

permissions:
    contents: read

on:
    push:
        branches:
            - "**"
        paths:
            - "src/client/**"
            - "src/modules/**"
            - ".github/workflows/test-bug-client.yml"
    pull_request:
        branches:
            - "main"
        paths:
            - "src/client/**"
            - "src/modules/**"
            - ".github/workflows/test-bug-client.yml"

jobs:
    client-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22]
        steps:
            - uses: actions/checkout@v6

            - name: send slack start message
              id: slack-start
              if: ${{ github.event_name != 'pull_request' }}
              uses: ./.github/actions/slack-run-start
              with:
                  message_prefix: Workflow running

            - uses: actions/setup-node@v6
              name: Client Build & Test using Node.js ${{ matrix.node-version }}
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: cd src/client && npm test
            - run: cd src/client && npm run build --if-present

            - name: update slack message
              if: ${{ always() && steps.slack-start.outputs.ts != '' }}
              uses: ./.github/actions/slack-run-finish
              with:
                  channel_id: ${{ steps.slack-start.outputs.channel_id }}
                  ts: ${{ steps.slack-start.outputs.ts }}
                  status: ${{ job.status }}
                  message_prefix: Workflow
