name: Version Bump

on:
    push:
        branches:
            - main

jobs:
    version:
        runs-on: self-hosted
        if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
            - run: npm version patch -m "[RELEASE] %s"
            - run: git push
